### ISSUE TITLE
Unresponsive after decrypting 2 - 3 titles - Win 10

### ISSUE THREAD

**Issue by abo3skr2019** [Xpl0itU/WiiUDownloader#68]
frozen 3 times

once after decrypting smash

another decrypting 
bayonetta 2

this is the third time
![image](https://github.com/Xpl0itU/WiiUDownloader/assets/68832286/676019a1-fa6c-4aff-b546-25eea4ea84fc)

Specs
R7 2700
32gb c16 3600mhz

**Comment by Xpl0itU** [comment]
Should be fixed with v2.0

**Comment by albertowd** [comment]
So it is still happening to me with those exact same title on v2.60!
ZoombieU also hangs on decryption.
Is there a log so we can see what happened? Because the action can`t be cancelled, but the main window closes with no issue the entire app.

![Image](https://github.com/user-attachments/assets/bea968de-bbf4-4b90-8320-3260ecaa9aa9)
