### ISSUE TITLE
Some issues with v2.0 on Mac

### ISSUE THREAD

**Issue by GreetingsIExist** [Xpl0itU/WiiUDownloader#69]
**Listing** - Lists all regions even after selecting just one.
![Captura de pantalla 2023-07-19 a la(s) 8 13 49 a m](https://github.com/Xpl0itU/WiiUDownloader/assets/139987032/18b0b74b-5998-4de8-9da9-6e57dd8143fb)

**Downloading** - Only downloads two files (at least when downloading Wind Waker HD USA), nothing else notable happend after finishing with those two files.
https://github.com/Xpl0itU/WiiUDownloader/assets/139987032/5c5306dd-8283-42ef-9c5b-b182b94f6374

_Program was ran on a Mac Mini M2 Pro, macOS Sonoma Developer Beta._

**Comment by Xpl0itU** [comment]
Got it, working on a fix, due to a lot of issues present in v2.0, I decided to temporarily remove it

**Comment by Xpl0itU** [comment]
Coud you try with v2.1?

**Comment by GreetingsIExist** [comment]
I'm afraid that it still has issues in my case. I did notice, however, that when browsing through the tabs (Game, Update, DLC...) the selected regions are respected. It's when using the Search Bar that the settings are ignored.
![Captura de pantalla 2023-07-19 a la(s) 12 15 39 p m](https://github.com/Xpl0itU/WiiUDownloader/assets/139987032/d144dba0-52a1-4acf-af4d-d5c75e8b1db2)
![Captura de pantalla 2023-07-19 a la(s) 12 15 48 p m](https://github.com/Xpl0itU/WiiUDownloader/assets/139987032/09eaef73-19f8-4135-9e09-9375581457fe)

This warning also appeared...
![Captura de pantalla 2023-07-19 a la(s) 12 16 01 p m](https://github.com/Xpl0itU/WiiUDownloader/assets/139987032/b3b6ccd7-db79-40fe-bda7-bcab96d6048c)
Warn: "(null)"
An obsolete API that will be deleted is being used. Communicate with the developer in order to obtain an updated version.

**Comment by Xpl0itU** [comment]
I just fixed the region issue when searching and the warning about the obsolete API, will be on the next version, however, I can't reproduce the wind waker hd USA problems you have, everytime I download it, it works just fine, maybe it's a problem with your internet? Could you try this build too just in case? [https://we.tl/t-l8c0lZUkhe](https://we.tl/t-l8c0lZUkhe)

**Comment by Janssonn91** [comment]
> I just fixed the region issue when searching and the warning about the obsolete API, will be on the next version, however, I can't reproduce the wind waker hd USA problems you have, everytime I download it, it works just fine, maybe it's a problem with your internet? Could you try this build too just in case? https://we.tl/t-1efyiWaQmL

I am using version 2.1 and getting same issues. Using Macbook pro (Intel version) and cannot download anything. When I place anything in queue it only downloads "title.tik" and "title.tmd".

**Comment by Xpl0itU** [comment]
I made v2.2, which adds error logging, please try it and see what happens

**Comment by Janssonn91** [comment]
Once it gets selected (when I press add to queue), nothing happens. Don't know if it should(?)... When I press Download queue, it crashes without any prompts, errors or anything.

**Comment by Xpl0itU** [comment]
Well, it should at least check the box on the title’s row, does it do that?

**Comment by Janssonn91** [comment]
The box gets checked when I click "Add to queue", yes. But it did before in v2.1 as well.

**Comment by Xpl0itU** [comment]
What os are you using?

**Comment by Janssonn91** [comment]
Ventura (13.4.1(c))

**Comment by Janssonn91** [comment]
`(<unknown>:1831): Gtk-WARNING **: 11:29:55.454: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

(<unknown>:1831): Gtk-WARNING **: 11:31:29.030: Could not find the icon 'user-home-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases

(<unknown>:1831): GLib-GIO-ERROR **: 11:31:29.067: No GSettings schemas are installed on the system
SIGTRAP: trace trap
PC=0x100cd54a7 m=0 sigcode=1
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x1002bcd30, 0xc0002711a0)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/cgocall.go:157 +0x5c fp=0xc000271178 sp=0xc000271140 pc=0x1000090fc
github.com/gotk3/gotk3/gtk._Cfunc_gtk_file_chooser_native_new(0x600000c95290, 0x10290b6b0, 0x2, 0x60000003b480, 0x600000038740)
	_cgo_gotypes.go:12233 +0x4d fp=0xc0002711a0 sp=0xc000271178 pc=0x10026be0d
github.com/gotk3/gotk3/gtk.FileChooserNativeDialogNew.func4(0x600000038740?, 0x6?, 0x2, 0x0?, 0x0?)
	/Users/runner/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/gtk/gtk_since_3_20.go:190 +0x7a fp=0xc000271200 sp=0xc0002711a0 pc=0x100289f9a
github.com/gotk3/gotk3/gtk.FileChooserNativeDialogNew({0x1003e969f?, 0x0?}, {0x10045a3e8, 0xc000128040}, 0x0?, {0x1003de628, 0x6}, {0x1003de562, 0x6})
	/Users/runner/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/gtk/gtk_since_3_20.go:190 +0x136 fp=0xc0002712a0 sp=0xc000271200 pc=0x100289d36
main.(*MainWindow).ShowAll.func2()
	/Users/runner/work/WiiUDownloader/WiiUDownloader/cmd/WiiUDownloader/mainwindow.go:257 +0x18c fp=0xc0002713b0 sp=0xc0002712a0 pc=0x10029f6cc
runtime.call16(0xc000115230, 0xc00011e2a0, 0x0, 0x0, 0x0, 0x0, 0xc0002718e0)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/asm_amd64.s:728 +0x49 fp=0xc0002713d0 sp=0xc0002713b0 pc=0x100068e09
runtime.reflectcall(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	<autogenerated>:1 +0x3c fp=0xc000271410 sp=0xc0002713d0 pc=0x10006d49c
reflect.Value.call({0x10030b060?, 0xc00011e2a0?, 0x10007da5b?}, {0x1003de0ec, 0x4}, {0x10069b950, 0x0, 0x10066b880?})
	/usr/local/Cellar/go/1.20.5/libexec/src/reflect/value.go:586 +0xb0b fp=0xc000271a00 sp=0xc000271410 pc=0x10008ce6b
reflect.Value.Call({0x10030b060?, 0xc00011e2a0?, 0x6000017615e0?}, {0x10069b950?, 0x1000439f1?, 0x0?})
	/usr/local/Cellar/go/1.20.5/libexec/src/reflect/value.go:370 +0xbc fp=0xc000271a78 sp=0xc000271a00 pc=0x10008c29c
github.com/gotk3/gotk3/glib.goMarshal(0x10?, 0x0, 0x1, 0x7ff7bfefe380, 0x1000096c6?, 0xc0000061a0?)
	/Users/runner/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/glib/glib.go:271 +0xa05 fp=0xc000271d08 sp=0xc000271a78 pc=0x10025e305
_cgoexp_b565b27e8aff_goMarshal(0x1?)
	_cgo_gotypes.go:6421 +0x32 fp=0xc000271d48 sp=0xc000271d08 pc=0x100262b92
runtime.cgocallbackg1(0x100262b60, 0xc000271ef8?, 0x0)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/cgocall.go:315 +0x2a4 fp=0xc000271e10 sp=0xc000271d48 pc=0x1000095e4
runtime.cgocallbackg(0xc0000061a0?, 0x300000002?, 0xc0000061a0?)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/cgocall.go:234 +0x109 fp=0xc000271ea0 sp=0xc000271e10 pc=0x1000092a9
runtime.cgocallbackg(0x100262b60, 0x7ff7bfefe1b0, 0x0)
	<autogenerated>:1 +0x2f fp=0xc000271ec8 sp=0xc000271ea0 pc=0x10006d04f
runtime.cgocallback(0x100009125, 0x1002b2650, 0xc000135f58)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/asm_amd64.s:998 +0xb4 fp=0xc000271ef0 sp=0xc000271ec8 pc=0x10006a8f4
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/asm_amd64.s:463 fp=0xc000271ef8 sp=0xc000271ef0 pc=0x1000688c0
runtime.cgocall(0x1002b2650, 0xc000271f58)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/cgocall.go:167 +0x85 fp=0xc000271f30 sp=0xc000271ef8 pc=0x100009125
github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
	_cgo_gotypes.go:17478 +0x45 fp=0xc000271f58 sp=0xc000271f30 pc=0x10026cec5
github.com/gotk3/gotk3/gtk.Main(...)
	/Users/runner/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/gtk/gtk.go:1242
main.Main(...)
	/Users/runner/work/WiiUDownloader/WiiUDownloader/cmd/WiiUDownloader/mainwindow.go:595
main.main()
	/Users/runner/work/WiiUDownloader/WiiUDownloader/cmd/WiiUDownloader/main.go:9 +0x31 fp=0xc000271f80 sp=0xc000271f58 pc=0x10029c711
runtime.main()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:250 +0x207 fp=0xc000271fe0 sp=0xc000271f80 pc=0x10003b767
runtime.goexit()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000271fe8 sp=0xc000271fe0 pc=0x10006ab01

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc00004afb0 sp=0xc00004af90 pc=0x10003bb96
runtime.goparkunlock(...)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:387
runtime.forcegchelper()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:305 +0xb0 fp=0xc00004afe0 sp=0xc00004afb0 pc=0x10003b9d0
runtime.goexit()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00004afe8 sp=0xc00004afe0 pc=0x10006ab01
created by runtime.init.6
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc00004b780 sp=0xc00004b760 pc=0x10003bb96
runtime.goparkunlock(...)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgcsweep.go:319 +0xde fp=0xc00004b7c8 sp=0xc00004b780 pc=0x100028b3e
runtime.gcenable.func1()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:178 +0x26 fp=0xc00004b7e0 sp=0xc00004b7c8 pc=0x10001dd66
runtime.goexit()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00004b7e8 sp=0xc00004b7e0 pc=0x10006ab01
created by runtime.gcenable
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000072000?, 0x100456098?, 0x0?, 0x0?, 0x0?)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc00004bf70 sp=0xc00004bf50 pc=0x10003bb96
runtime.goparkunlock(...)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x10066bea0)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc00004bfa0 sp=0xc00004bf70 pc=0x1000269d3
runtime.bgscavenge(0x0?)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc00004bfc8 sp=0xc00004bfa0 pc=0x100026fc5
runtime.gcenable.func2()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:179 +0x26 fp=0xc00004bfe0 sp=0xc00004bfc8 pc=0x10001dd06
runtime.goexit()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00004bfe8 sp=0xc00004bfe0 pc=0x10006ab01
created by runtime.gcenable
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x0?, 0x10040e438?, 0x10?, 0xa0?, 0x1000000010?)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc00005be28 sp=0xc00005be08 pc=0x10003bb96
runtime.runfinq()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mfinal.go:193 +0x107 fp=0xc00005bfe0 sp=0xc00005be28 pc=0x10001cda7
runtime.goexit()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00005bfe8 sp=0xc00005bfe0 pc=0x10006ab01
created by runtime.createfing
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mfinal.go:163 +0x45

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc000046750 sp=0xc000046730 pc=0x10003bb96
runtime.gcBgMarkWorker()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000467e0 sp=0xc000046750 pc=0x10001fad1
runtime.goexit()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000467e8 sp=0xc0000467e0 pc=0x10006ab01
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:1199 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x6906bd9ce00?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc000094750 sp=0xc000094730 pc=0x10003bb96
runtime.gcBgMarkWorker()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000947e0 sp=0xc000094750 pc=0x10001fad1
runtime.goexit()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000947e8 sp=0xc0000947e0 pc=0x10006ab01
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:1199 +0x25

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x6906bd9e042?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc000094f50 sp=0xc000094f30 pc=0x10003bb96
runtime.gcBgMarkWorker()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:1275 +0xf1 fp=0xc000094fe0 sp=0xc000094f50 pc=0x10001fad1
runtime.goexit()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000094fe8 sp=0xc000094fe0 pc=0x10006ab01
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:1199 +0x25

goroutine 5 [GC worker (idle)]:
runtime.gopark(0x6906bdb1ba0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc00004c750 sp=0xc00004c730 pc=0x10003bb96
runtime.gcBgMarkWorker()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:1275 +0xf1 fp=0xc00004c7e0 sp=0xc00004c750 pc=0x10001fad1
runtime.goexit()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00004c7e8 sp=0xc00004c7e0 pc=0x10006ab01
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:1199 +0x25

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x6906bd9cc82?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc000046f50 sp=0xc000046f30 pc=0x10003bb96
runtime.gcBgMarkWorker()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:1275 +0xf1 fp=0xc000046fe0 sp=0xc000046f50 pc=0x10001fad1
runtime.goexit()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000046fe8 sp=0xc000046fe0 pc=0x10006ab01
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:1199 +0x25

goroutine 36 [GC worker (idle)]:
runtime.gopark(0x6906bdafd00?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc000095750 sp=0xc000095730 pc=0x10003bb96
runtime.gcBgMarkWorker()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000957e0 sp=0xc000095750 pc=0x10001fad1
runtime.goexit()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000957e8 sp=0xc0000957e0 pc=0x10006ab01
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:1199 +0x25

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x6906bdb6c85?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc00004cf50 sp=0xc00004cf30 pc=0x10003bb96
runtime.gcBgMarkWorker()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:1275 +0xf1 fp=0xc00004cfe0 sp=0xc00004cf50 pc=0x10001fad1
runtime.goexit()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00004cfe8 sp=0xc00004cfe0 pc=0x10006ab01
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:1199 +0x25

goroutine 50 [GC worker (idle)]:
runtime.gopark(0x6906bdafdac?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc000090750 sp=0xc000090730 pc=0x10003bb96
runtime.gcBgMarkWorker()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000907e0 sp=0xc000090750 pc=0x10001fad1
runtime.goexit()
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000907e8 sp=0xc0000907e0 pc=0x10006ab01
created by runtime.gcBgMarkStartWorkers
	/usr/local/Cellar/go/1.20.5/libexec/src/runtime/mgc.go:1199 +0x25

rax    0x0
rbx    0x1
rcx    0x7ff84967c640
rdx    0x11e
rdi    0x1
rsi    0x0
rbp    0x7ff7bfefcb60
rsp    0x7ff7bfefcb50
r8     0x7ff849687480
r9     0x7f
r10    0x1b00
r11    0x6000000016b0
r12    0x1
r13    0x0
r14    0x6
r15    0x4
rip    0x100cd54a7
rflags 0x202
cs     0x2b
fs     0x0
gs     0x0
`

**Comment by Xpl0itU** [comment]
Both the 2 file only download and the crash are fixed on v2.3 [https://github.com/Xpl0itU/WiiUDownloader/releases/tag/v2.3](https://github.com/Xpl0itU/WiiUDownloader/releases/tag/v2.3)

**Comment by Janssonn91** [comment]
I cannot open the app.
[img of error](https://i.imgur.com/IL3duph.png)

**Comment by Xpl0itU** [comment]
I made a mistake, currently compiling a release version (v2.4), hold on

**Comment by Xpl0itU** [comment]
Issues are fixed with v2.4

**Comment by Janssonn91** [comment]
Working now :)

**Comment by Xpl0itU** [comment]
Awesome, closing this issue then

**Comment by maddovr** [comment]
Crashing on latest with ventura 13.4.1, here is the log
```objc[1715]: Class GNotificationCenterDelegate is implemented in both /Applications/WiiUDownloader.app/Contents/MacOS/lib/libgio-2.0.0.dylib (0x100b0c3b0) and /usr/local/Cellar/glib/2.76.4/lib/libgio-2.0.0.dylib (0x1308046b0). One of the two will be used. Which one is undefined.

(<unknown>:1715): GdkPixbuf-CRITICAL **: 19:21:09.000: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(<unknown>:1715): GdkPixbuf-CRITICAL **: 19:21:09.000: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(<unknown>:1715): GdkPixbuf-CRITICAL **: 19:21:09.000: gdk_pixbuf_set_option: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(<unknown>:1715): GdkPixbuf-CRITICAL **: 19:21:09.000: gdk_pixbuf_set_option: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(<unknown>:1715): GdkPixbuf-CRITICAL **: 19:21:09.000: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(<unknown>:1715): GdkPixbuf-CRITICAL **: 19:21:09.000: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(<unknown>:1715): GdkPixbuf-CRITICAL **: 19:21:09.000: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(<unknown>:1715): GdkPixbuf-CRITICAL **: 19:21:09.000: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(<unknown>:1715): GdkPixbuf-CRITICAL **: 19:21:09.000: gdk_pixbuf_scale_simple: assertion 'GDK_IS_PIXBUF (src)' failed

(<unknown>:1715): Gtk-WARNING **: 19:21:09.000: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

(<unknown>:1715): GLib-CRITICAL **: 19:21:09.000: g_propagate_error: assertion 'src != NULL' failed
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x101570567]

runtime stack:
runtime.throw({0x1003fb8c7?, 0x100cf9a01?})
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/panic.go:1047 +0x5d fp=0x7000066a6710 sp=0x7000066a66e0 pc=0x100037fbd
runtime.sigpanic()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/signal_unix.go:825 +0x3e9 fp=0x7000066a6770 sp=0x7000066a6710 pc=0x10004e489

goroutine 1 [syscall]:
runtime.cgocall(0x1002d1fe0, 0xc000187ba0)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/cgocall.go:157 +0x5c fp=0xc000187b78 sp=0xc000187b40 pc=0x100007ddc
github.com/gotk3/gotk3/gtk._Cfunc_gtk_widget_show_all(0x101f266d0)
	_cgo_gotypes.go:34958 +0x45 fp=0xc000187ba0 sp=0xc000187b78 pc=0x100274985
github.com/gotk3/gotk3/gtk.(*Widget).ShowAll.func1(0xc0002e55f8?)
	/Users/runner/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/gtk/widget.go:484 +0x3f fp=0xc000187bd8 sp=0xc000187ba0 pc=0x100291d7f
github.com/gotk3/gotk3/gtk.(*Widget).ShowAll(0x1003eca80?)
	/Users/runner/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/gtk/widget.go:484 +0x19 fp=0xc000187bf0 sp=0xc000187bd8 pc=0x100291d19
main.(*MainWindow).ShowAll(0xc0000000c0)
	/Users/runner/work/WiiUDownloader/WiiUDownloader/cmd/WiiUDownloader/mainwindow.go:428 +0x262e fp=0xc000187e90 sp=0xc000187bf0 pc=0x1002a9b8e
main.main()
	/Users/runner/work/WiiUDownloader/WiiUDownloader/cmd/WiiUDownloader/main.go:36 +0x2ed fp=0xc000187f80 sp=0xc000187e90 pc=0x1002a69cd
runtime.main()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:250 +0x207 fp=0xc000187fe0 sp=0xc000187f80 pc=0x10003a867
runtime.goexit()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000187fe8 sp=0xc000187fe0 pc=0x100069f41

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc00003efb0 sp=0xc00003ef90 pc=0x10003ac96
runtime.goparkunlock(...)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:387
runtime.forcegchelper()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:305 +0xb0 fp=0xc00003efe0 sp=0xc00003efb0 pc=0x10003aad0
runtime.goexit()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00003efe8 sp=0xc00003efe0 pc=0x100069f41
created by runtime.init.6
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc00003f780 sp=0xc00003f760 pc=0x10003ac96
runtime.goparkunlock(...)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mgcsweep.go:278 +0x8e fp=0xc00003f7c8 sp=0xc00003f780 pc=0x10002794e
runtime.gcenable.func1()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mgc.go:178 +0x26 fp=0xc00003f7e0 sp=0xc00003f7c8 pc=0x10001cbc6
runtime.goexit()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00003f7e8 sp=0xc00003f7e0 pc=0x100069f41
created by runtime.gcenable
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000064000?, 0x100465fc8?, 0x1?, 0x0?, 0x0?)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc00003ff70 sp=0xc00003ff50 pc=0x10003ac96
runtime.goparkunlock(...)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x100684a80)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc00003ffa0 sp=0xc00003ff70 pc=0x100025833
runtime.bgscavenge(0x0?)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc00003ffc8 sp=0xc00003ffa0 pc=0x100025e05
runtime.gcenable.func2()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mgc.go:179 +0x26 fp=0xc00003ffe0 sp=0xc00003ffc8 pc=0x10001cb66
runtime.goexit()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00003ffe8 sp=0xc00003ffe0 pc=0x100069f41
created by runtime.gcenable
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x1a0?, 0x100685040?, 0x20?, 0x75?, 0xc00003e770?)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc00003e628 sp=0xc00003e608 pc=0x10003ac96
runtime.runfinq()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mfinal.go:193 +0x107 fp=0xc00003e7e0 sp=0xc00003e628 pc=0x10001bc07
runtime.goexit()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00003e7e8 sp=0xc00003e7e0 pc=0x100069f41
created by runtime.createfing
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mfinal.go:163 +0x45
```

**Comment by Xpl0itU** [comment]
When does it happen? Opening? If it’s opening, try again, it should work, it has a small chance crashing on starting

**Comment by maddovr** [comment]
> When does it happen? Opening? If it’s opening, try again, it should work, it has a small chance crashing on starting

Yes on opening, tried multiple times, it crashes immediately. I'm on 13.4.1 (c) and intel Mac.

**Comment by Xpl0itU** [comment]
Should be fixed with v2.18

**Comment by maddovr** [comment]
Nope, still not fixed. It now lasts until I can see the top global menu say "Wii U downloader" for an instant but it crashes before showing any window.

**Comment by Xpl0itU** [comment]
Mind sending a crashlog once again?

**Comment by Xpl0itU** [comment]
Also, are you sure you got v2.18? I can't replicate the crash with my M1 MacBook Pro or my clean macOS Big Sur VM

**Comment by maddovr** [comment]
Here's 2.19 crash log, uninstalled and reinstalled with a new download.
``` /Applications/WiiUDownloader.app/Contents/MacOS/WiiUDownloader
objc[6201]: Class GNotificationCenterDelegate is implemented in both /Applications/WiiUDownloader.app/Contents/MacOS/lib/libgio-2.0.0.dylib (0x100b103b0) and /usr/local/Cellar/glib/2.76.4/lib/libgio-2.0.0.dylib (0x1306026b0). One of the two will be used. Which one is undefined.

(<unknown>:6201): GdkPixbuf-CRITICAL **: 00:05:05.346: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(<unknown>:6201): GdkPixbuf-CRITICAL **: 00:05:05.346: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(<unknown>:6201): GdkPixbuf-CRITICAL **: 00:05:05.346: gdk_pixbuf_set_option: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(<unknown>:6201): GdkPixbuf-CRITICAL **: 00:05:05.346: gdk_pixbuf_set_option: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(<unknown>:6201): GdkPixbuf-CRITICAL **: 00:05:05.346: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(<unknown>:6201): GdkPixbuf-CRITICAL **: 00:05:05.346: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(<unknown>:6201): GdkPixbuf-CRITICAL **: 00:05:05.346: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(<unknown>:6201): GdkPixbuf-CRITICAL **: 00:05:05.346: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(<unknown>:6201): GdkPixbuf-CRITICAL **: 00:05:05.346: gdk_pixbuf_scale_simple: assertion 'GDK_IS_PIXBUF (src)' failed

(<unknown>:6201): Gtk-WARNING **: 00:05:05.346: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

(<unknown>:6201): GLib-CRITICAL **: 00:05:05.346: g_propagate_error: assertion 'src != NULL' failed
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x101574567]

runtime stack:
runtime.throw({0x1003fdc47?, 0x100cfda01?})
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/panic.go:1047 +0x5d fp=0x7ff7bfefe4c0 sp=0x7ff7bfefe490 pc=0x10003809d
runtime.sigpanic()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/signal_unix.go:825 +0x3e9 fp=0x7ff7bfefe520 sp=0x7ff7bfefe4c0 pc=0x10004e569

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x1002d3ab0, 0xc00010f140)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/cgocall.go:157 +0x5c fp=0xc00010f118 sp=0xc00010f0e0 pc=0x100007ebc
github.com/gotk3/gotk3/gtk._Cfunc_gtk_widget_show(0x102e080d0)
	_cgo_gotypes.go:34945 +0x45 fp=0xc00010f140 sp=0xc00010f118 pc=0x1002757c5
github.com/gotk3/gotk3/gtk.(*Widget).Show.func1(0xc000247788?)
	/Users/runner/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/gtk/widget.go:253 +0x3f fp=0xc00010f178 sp=0xc00010f140 pc=0x1002933df
github.com/gotk3/gotk3/gtk.(*Widget).Show(0xc00009e000?)
	/Users/runner/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/gtk/widget.go:253 +0x19 fp=0xc00010f190 sp=0xc00010f178 pc=0x100293379
main.main.func1()
	/Users/runner/work/WiiUDownloader/WiiUDownloader/cmd/WiiUDownloader/main.go:46 +0x79 fp=0xc00010f1e0 sp=0xc00010f190 pc=0x1002a84d9
runtime.call16(0xc00007d050, 0xc0000121b0, 0x0, 0x0, 0x0, 0x0, 0xc00010f710)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/asm_amd64.s:728 +0x49 fp=0xc00010f200 sp=0xc00010f1e0 pc=0x100068329
runtime.reflectcall(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	<autogenerated>:1 +0x3c fp=0xc00010f240 sp=0xc00010f200 pc=0x10006c9bc
reflect.Value.call({0x100319a40?, 0xc0000121b0?, 0x10007cf7b?}, {0x1003ee917, 0x4}, {0x1006b8590, 0x0, 0x100688420?})
	/usr/local/Cellar/go/1.20.7/libexec/src/reflect/value.go:586 +0xb0b fp=0xc00010f830 sp=0xc00010f240 pc=0x10008c38b
reflect.Value.Call({0x100319a40?, 0xc0000121b0?, 0x600001722320?}, {0x1006b8590?, 0x100042385?, 0xc0000061a0?})
	/usr/local/Cellar/go/1.20.7/libexec/src/reflect/value.go:370 +0xbc fp=0xc00010f8a8 sp=0xc00010f830 pc=0x10008b7bc
github.com/gotk3/gotk3/glib.goMarshal(0x100066775?, 0x0, 0x1, 0x7ff7bfefef30, 0xc00007d020?, 0x30?)
	/Users/runner/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/glib/glib.go:271 +0xa05 fp=0xc00010fb38 sp=0xc00010f8a8 pc=0x100262065
_cgoexp_b565b27e8aff_goMarshal(0x0?)
	_cgo_gotypes.go:6421 +0x32 fp=0xc00010fb78 sp=0xc00010fb38 pc=0x100266e32
runtime.cgocallbackg1(0x100266e00, 0x100042c31?, 0x0)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/cgocall.go:315 +0x2a4 fp=0xc00010fc40 sp=0xc00010fb78 pc=0x1000083a4
runtime.cgocallbackg(0xc0000061a0?, 0x300000002?, 0xc0000061a0?)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/cgocall.go:234 +0x109 fp=0xc00010fcd0 sp=0xc00010fc40 pc=0x100008069
runtime.cgocallbackg(0x100266e00, 0x7ff7bfefed60, 0x0)
	<autogenerated>:1 +0x2f fp=0xc00010fcf8 sp=0xc00010fcd0 pc=0x10006c56f
runtime.cgocallback(0x100007ee5, 0x1002af960, 0xc00010fd88)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/asm_amd64.s:998 +0xb4 fp=0xc00010fd20 sp=0xc00010fcf8 pc=0x100069e14
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/asm_amd64.s:463 fp=0xc00010fd28 sp=0xc00010fd20 pc=0x100067de0
runtime.cgocall(0x1002af960, 0xc00010fd88)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/cgocall.go:167 +0x85 fp=0xc00010fd60 sp=0xc00010fd28 pc=0x100007ee5
github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x101f0e410, 0x0, 0x6000000066e0)
	_cgo_gotypes.go:1578 +0x4c fp=0xc00010fd88 sp=0xc00010fd60 pc=0x10025d38c
github.com/gotk3/gotk3/glib.(*Application).Run.func4(0x6000000066e0?, {0x0?, 0x0, 0x600000c169d0?}, 0xd?)
	/Users/runner/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/glib/application.go:185 +0x7b fp=0xc00010fdc8 sp=0xc00010fd88 pc=0x10026031b
github.com/gotk3/gotk3/glib.(*Application).Run(0x1003f943c?, {0x0?, 0x0, 0x0})
	/Users/runner/go/pkg/mod/github.com/gotk3/gotk3@v0.6.2/glib/application.go:185 +0x17f fp=0xc00010fe88 sp=0xc00010fdc8 pc=0x10026023f
main.main()
	/Users/runner/work/WiiUDownloader/WiiUDownloader/cmd/WiiUDownloader/main.go:48 +0x39e fp=0xc00010ff80 sp=0xc00010fe88 pc=0x1002a83fe
runtime.main()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:250 +0x207 fp=0xc00010ffe0 sp=0xc00010ff80 pc=0x10003a947
runtime.goexit()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00010ffe8 sp=0xc00010ffe0 pc=0x10006a021

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc00003efb0 sp=0xc00003ef90 pc=0x10003ad76
runtime.goparkunlock(...)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:387
runtime.forcegchelper()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:305 +0xb0 fp=0xc00003efe0 sp=0xc00003efb0 pc=0x10003abb0
runtime.goexit()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00003efe8 sp=0xc00003efe0 pc=0x10006a021
created by runtime.init.6
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc00003f780 sp=0xc00003f760 pc=0x10003ad76
runtime.goparkunlock(...)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mgcsweep.go:278 +0x8e fp=0xc00003f7c8 sp=0xc00003f780 pc=0x100027a2e
runtime.gcenable.func1()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mgc.go:178 +0x26 fp=0xc00003f7e0 sp=0xc00003f7c8 pc=0x10001cca6
runtime.goexit()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00003f7e8 sp=0xc00003f7e0 pc=0x10006a021
created by runtime.gcenable
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00006c000?, 0x1004683e0?, 0x1?, 0x0?, 0x0?)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc00003ff70 sp=0xc00003ff50 pc=0x10003ad76
runtime.goparkunlock(...)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x100688ae0)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc00003ffa0 sp=0xc00003ff70 pc=0x100025913
runtime.bgscavenge(0x0?)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc00003ffc8 sp=0xc00003ffa0 pc=0x100025ee5
runtime.gcenable.func2()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mgc.go:179 +0x26 fp=0xc00003ffe0 sp=0xc00003ffc8 pc=0x10001cc46
runtime.goexit()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00003ffe8 sp=0xc00003ffe0 pc=0x10006a021
created by runtime.gcenable
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x1a0?, 0x1006890a0?, 0x60?, 0x78?, 0xc00003e770?)
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/proc.go:381 +0xd6 fp=0xc00003e628 sp=0xc00003e608 pc=0x10003ad76
runtime.runfinq()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mfinal.go:193 +0x107 fp=0xc00003e7e0 sp=0xc00003e628 pc=0x10001bce7
runtime.goexit()
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00003e7e8 sp=0xc00003e7e0 pc=0x10006a021
created by runtime.createfing
	/usr/local/Cellar/go/1.20.7/libexec/src/runtime/mfinal.go:163 +0x45
```
